Adding an optional authentication feature to eventlog
MastodonC/kixi.eventlog pull request #5
Opened 2016-10-18 14:43 UTC by elisehuard

* flag to add authentication to eventlog if needed
* the public key gets loaded from a designated s3 bucket in the docker image
* upgraded to clojure 1.8
* removing uberimage in leiningen in favour of a vanilla docker file, to match other repos

2016-10-18 14:54 UTC, otfrom requested changes
A few questions and a tweak on msg size.

2016-10-18 14:54 UTC, otfrom commented on resources/auth_pubkey.pem
> +-----BEGIN PUBLIC KEY-----
is this a dummy?

2016-10-18 14:54 UTC, otfrom commented on resources/eventlog.edn
> +                            :production "http://heimdall.marathon.mesos:3000"}} }
more dummy values or are they OK?

2016-10-18 14:54 UTC, otfrom commented on src/kixi/eventlog/application.clj
> +         max-message-size  (or (System/getenv "TOPIC_MAX_MESSAGE_SIZE") "1000000")
I think we should go for a multiple here rather than a single value and it should be `(* 16 1024 1024)`

2016-10-18 14:54 UTC, otfrom commented on src/kixi/eventlog/application.clj
> +                               "flight_events01 hotel_events01")
I don't think we need these as defaults in the code any more or we can choose other default values.

2016-10-18 14:54 UTC, otfrom commented on src/kixi/eventlog/web_server.clj
> +                (* 16 1024 1024)}
this is the Max Message Size. I think we should factor this out to MAX_MESSAGE_SIZE somewhere else.

2016-10-18 15:03 UTC, elisehuard commented on resources/auth_pubkey.pem
> +-----BEGIN PUBLIC KEY-----
Yes, I guess it's a dummy, should actually correspond to something in heimdall or be removed altogether

2016-10-18 15:03 UTC, elisehuard commented on resources/eventlog.edn
> +                            :production "http://heimdall.marathon.mesos:3000"}} }
I'll make this an .example file

2016-10-18 16:22 UTC, elisehuard commented on resources/eventlog.edn
> +                            :production "http://heimdall.marathon.mesos:3000"}} }
actually,no, this is ok

2016-10-19 16:22 UTC, otfrom requested changes
Just the one string constant that I think should be 16MB rather than 10MB

2016-10-19 16:22 UTC, otfrom commented on src/kixi/eventlog/application.clj
> +         max-message-size  (or (System/getenv "TOPIC_MAX_MESSAGE_SIZE") "1048576")
How about:

```
max-message-size  (or (System/getenv "TOPIC_MAX_MESSAGE_SIZE") (str (* 16 1024 1024)))
```

2016-10-19 16:26 UTC, otfrom approved these changes

2016-10-19 16:26 UTC, otfrom commented
:shipit:

2016-10-19 16:28 UTC, merged